CREATE DATABASE IF NOT EXISTS doce_saep_db;
USE doce_saep_db;

CREATE TABLE USUARIO (
    USU_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USU_NOME  VARCHAR(255),
    USU_EMAIL  VARCHAR(255) UNIQUE,
    USU_SENHA VARCHAR(255)
);

CREATE TABLE DOCES (
    DOCE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DOCE_MARCA VARCHAR(255),
    DOCE_TIPO VARCHAR(255),
    DOCE_DATA_VALIDADE DATE,
    DOCE_FORMATO VARCHAR(255),
    DOCE_TAMANHO VARCHAR(255),
    FK_USU_ID INTEGER
);

CREATE TABLE ESTOQUE (
    ESTOQUE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ESTOQUE_QUANTIDADE INTEGER,
    FK_DOCE_ID  INTEGER 
);

CREATE TABLE LOGS (
    LOG_ID  INTEGER AUTO_INCREMENT PRIMARY KEY,
    LOG_DESCRICAO VARCHAR(255),
    LOG_DATA_HORA DATE
);
 
ALTER TABLE DOCES ADD CONSTRAINT FK_DOCES_2
    FOREIGN KEY (FK_USU_ID)
    REFERENCES USUARIO (USU_ID);
 
ALTER TABLE ESTOQUE ADD CONSTRAINT FK_ESTOQUE_2
    FOREIGN KEY (FK_DOCE_ID)
    REFERENCES DOCES (DOCE_ID);
    
INSERT INTO USUARIO (USU_NOME, USU_EMAIL, USU_SENHA)
VALUES 
('Maria Silva', 'maria@example.com', '12345'),
('João Pereira', 'joao@example.com', 'senha123'),
('Ana Costa', 'ana@example.com', 'abc123');

INSERT INTO DOCES (DOCE_MARCA, DOCE_TIPO, DOCE_DATA_VALIDADE, DOCE_FORMATO, DOCE_TAMANHO, FK_USU_ID)
VALUES
('Nestlé', 'Chocolate', '2025-12-01', 'Quadrado', 'Pequeno', 1),
('Arcor', 'Bala', '2026-03-10', 'Redonda', 'Médio', 2),
('Lacta', 'Bombom', '2025-08-20', 'Oval', 'Grande', 3);

INSERT INTO ESTOQUE (ESTOQUE_QUANTIDADE, FK_DOCE_ID)
VALUES
(150, 1),
(300, 2),
(80, 3);

INSERT INTO LOGS (LOG_DESCRICAO, LOG_DATA_HORA)
VALUES
('Usuário Maria cadastrou um novo doce.', '2025-10-07'),
('Estoque atualizado para o doce Arcor.', '2025-10-07'),
('Usuário Ana removeu um item do estoque.', '2025-10-07');

SELECT * FROM DOCES;