CREATE DATABASE IF NOT EXISTS BD_ELETRONICO;
USE BD_ELETRONICO;

CREATE TABLE USUARIO (
    USU_ID INT AUTO_INCREMENT PRIMARY KEY,
    USU_NOME VARCHAR(100) NOT NULL,
    USU_EMAIL VARCHAR(150) UNIQUE NOT NULL,
    USU_SENHA VARCHAR(100) NOT NULL
);

CREATE TABLE ELETRONICOS (
    ELETRONICO_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(250),
    MARCA VARCHAR(100),
    CATEGORIA VARCHAR(100),
    FK_USUARIO_ID INT,
    FORNECEDOR VARCHAR(100),
    POTENCIA VARCHAR(50),
    CONSUMO VARCHAR(50),
    GARANTIA DATE,
    PRIORIDADE VARCHAR(50),
    CONSTRAINT FK_ELETRONICOS_USUARIO FOREIGN KEY (FK_USUARIO_ID)
        REFERENCES USUARIO (USU_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE ESTOQUE (
    ESTOQUE_ID INT AUTO_INCREMENT PRIMARY KEY,
    QUANTIDADE INT,
    FK_ELETRO_ID INT,
    CONSTRAINT FK_ESTOQUE_ELETRONICO FOREIGN KEY (FK_ELETRO_ID)
        REFERENCES ELETRONICOS (ELETRONICO_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE LOGS (
    LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
    LOG_DESCRICAO VARCHAR(255),
    LOG_DATA_HORA DATETIME DEFAULT CURRENT_TIMESTAMP
);

USE BD_ELETRONICO;


INSERT INTO USUARIO (USU_NOME, USU_EMAIL, USU_SENHA)
VALUES
('João Silva', 'joao.silva@email.com', 'senha123'),
('Maria Oliveira', 'maria.oliveira@email.com', '12345abc'),
('Carlos Santos', 'carlos.santos@email.com', 'minhasenha');


INSERT INTO ELETRONICOS (NOME, MARCA, CATEGORIA, FK_USUARIO_ID, FORNECEDOR, POTENCIA, CONSUMO, GARANTIA, PRIORIDADE)
VALUES
('Smart TV 55','Samsung', 'TV', 1, 'TechDistribuidora', '200W', 'A+', '2026-05-20', 'Alta'),
('Geladeira Duplex 400L','LG', 'Geladeira', 2, 'FrioMax', '800W', 'B', '2027-03-15', 'Média'),
('Micro-ondas 20L','Philco', 'Micro-ondas', 3, 'EletroCenter', '1200W', 'A', '2025-12-10', 'Baixa');


INSERT INTO ESTOQUE (QUANTIDADE, FK_ELETRO_ID)
VALUES
(10, 1),
(5, 2),
(20, 3);


INSERT INTO LOGS (LOG_DESCRICAO)
VALUES
('Usuário João Silva adicionou um novo eletrônico.'),
('Atualização de estoque realizada para o produto LG Geladeira.'),
('Sistema iniciou rotina de backup automático.');

SELECT * FROM LOGS;